# Generated by Django 3.1.7 on 2021-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_auto_20210301_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tecnico_chamado',
            field=models.CharField(choices=[('SE', 'Selecione'), ('RA', 'Rafael'), ('EN', 'Endrio'), ('AN', 'ANDRÉ'), ('RU', 'RUI'), ('LA', 'LAURO'), ('LE', 'LAÉRCIO')], default='SE', max_length=2),
        ),
    ]
