# Generated by Django 3.1.7 on 2021-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_auto_20210301_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tecnico_chamado',
            field=models.CharField(choices=[('S', 'selecione'), ('R', 'Rafael W'), ('F', 'Fernando M'), ('A', 'André C')], default='S', max_length=1),
        ),
    ]
