# Generated by Django 3.1.7 on 2021-03-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0006_auto_20210301_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1),
        ),
    ]
