# Generated by Django 3.1.7 on 2021-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0007_chamado_status_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], max_length=1),
        ),
    ]
