# Generated by Django 3.1.7 on 2021-03-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0008_auto_20210301_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(choices=[('A', 'Aberto'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
