# Generated by Django 3.1.7 on 2021-03-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0009_auto_20210302_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(choices=[('A', 'Aberto'), ('R', 'Reprovado'), ('E', 'Encaminhado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
